DROP TABLE IF EXISTS user;
DROP TABLE IF EXISTS post;
DROP TABLE IF EXISTS product;
DROP TABLE IF EXISTS storage;


CREATE TABLE user (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  username TEXT UNIQUE NOT NULL,
  password TEXT NOT NULL
);

CREATE TABLE post (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  attendant_id INTEGER NOT NULL,
  created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  name TEXT NOT NULL,
  inventory INTEGER NOT NULL,
  FOREIGN KEY (attendant_id) REFERENCES user (id),
  FOREIGN KEY (product_id) REFERENCES product (id)
);

CREATE TABLE post_product (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    post_id INTEGER NOT NULL,
    product_id INTEGER NOT NULL,
    FOREIGN KEY (post_id) REFERENCES post (id),
    FOREIGN KEY (product_id) REFERENCES product (id),
)

CREATE TABLE product (
    id INTENGER PRIMARY KEY AUTOINCREMENT,
    name TEXT NOT NULL,
    price INTEGER NOT NULL,
    quantity_in_post INTEGER NOT NULL,
    quantity_in_storage INTEGER NOT NULL,
    cost INTEGER NOT NULL,
    created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
)

CREATE TABLE sales (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  id INTENGER PRIMARY KEY AUTOINCREMENT,
  income INTEGER NOT NULL,
  FOREIGN KEY (post_id) REFERENCES post (id),
)

CREATE TABLE sales_products (
  id INTENGER PRIMARY KEY AUTOINCREMENT,
  sale_id INTEGER NOT NULL,
  product_id INTEGER NOT NULL,
  FOREIGN KEY (sale_id) REFERENCES sale (id),
  FOREIGN KEY (product_id) REFERENCES product (id)
)
